# Generated by Django 3.2 on 2021-06-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text_index', models.CharField(default='FRIENDLY USER CLOUD', max_length=40)),
                ('subtitle_index', models.CharField(default='Przechowamy Twoje pliki :)', max_length=150)),
                ('footer', models.CharField(default='CREATED BY KRZYSZTOF IŁENDO, MARCIN GRABOWIECKI AND ŁUKASZ HOSSA', max_length=150)),
                ('login_link', models.CharField(default='LOGIN', max_length=40)),
                ('register_link', models.CharField(default='REGISTER', max_length=40)),
                ('welcome_user_files_view', models.CharField(default='WITAJ', max_length=50)),
                ('subtitle_files_view', models.CharField(default='Oto Twoje pliki', max_length=50)),
            ],
        ),
    ]
