# Generated by Django 3.2 on 2021-06-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='go_to_yout_files_button',
            field=models.CharField(default='Przejdź do swoich plików', max_length=40),
        ),
        migrations.AddField(
            model_name='context',
            name='logout_link',
            field=models.CharField(default='LOGOUT', max_length=40),
        ),
        migrations.AddField(
            model_name='context',
            name='welcome_logged_user_link',
            field=models.CharField(default='Welcome, ', max_length=40),
        ),
    ]
