# Generated by Django 3.2 on 2021-06-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_auto_20210610_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='context',
            old_name='go_to_yout_files_button',
            new_name='go_to_your_files_button',
        ),
    ]
