# Generated by Django 3.2 on 2021-06-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_customuser_used_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='share_link',
            field=models.CharField(default='', max_length=140),
        ),
    ]
